field: e2e7b70d-6b78-4367-a3b0-5287688756fa # Recipe Contents
fieldLayouts:
  593b534d-2478-4f55-b65d-0384723ee15f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 43fdb54f-db3c-413c-92df-25ae5412022f # Steps Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6e6e674c-e0bd-4dac-a514-dfd4379fff24
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: de664fed-a6a1-4507-b872-8b330ea95a9f # Steps Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fb093289-67fc-47ba-add8-6948d8017492
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: cffcbb85-5401-4380-ae3e-ce5aa7a5159a
        userCondition: null
fields:
  43fdb54f-db3c-413c-92df-25ae5412022f: # Steps Title
    columnSuffix: lozrglfz
    contentColumnType: text
    fieldGroup: null
    handle: stepsTitle
    instructions: null
    name: 'Steps Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  de664fed-a6a1-4507-b872-8b330ea95a9f: # Steps Content
    columnSuffix: shntrjru
    contentColumnType: text
    fieldGroup: null
    handle: stepsContent
    instructions: null
    name: 'Steps Content'
    searchable: false
    settings:
      addRowLabel: 'Add a row'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - 'Step Instructions'
                -
                  - handle
                  - stepInstructions
                -
                  - width
                  - ''
                -
                  - type
                  - multiline
      defaults: null
      maxRows: null
      minRows: null
      staticRows: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
handle: recipeSteps
name: 'Recipe Steps'
sortOrder: 4
