field: e2e7b70d-6b78-4367-a3b0-5287688756fa # Recipe Contents
fieldLayouts:
  80affb3a-6862-4cb9-a181-90470885c7b0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 9e9d3a3e-ff5f-4bd5-9183-cf66f813f9c1 # Body Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2eeabe3e-3088-4f80-87c0-865feb64c025
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8068b93b-b87a-40ac-b829-90b5078702ee
        userCondition: null
fields:
  9e9d3a3e-ff5f-4bd5-9183-cf66f813f9c1: # Body Content
    columnSuffix: scrnrdtl
    contentColumnType: text
    fieldGroup: null
    handle: bodyContent
    instructions: null
    name: 'Body Content'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: recipeCopy
name: 'Recipe Copy'
sortOrder: 3
