field: e2e7b70d-6b78-4367-a3b0-5287688756fa # Recipe Contents
fieldLayouts:
  a42663eb-cb6a-46b0-aba8-8ea49a4170e1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2e12d3c4-fabc-44a2-a889-45a7d07cb32b # Tip Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0b3cacb7-41a5-4421-b422-84c9b0e2b131
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 532bad87-e779-4e9e-af2d-f827ce6b225d
        userCondition: null
fields:
  2e12d3c4-fabc-44a2-a889-45a7d07cb32b: # Tip Content
    columnSuffix: atiosxeb
    contentColumnType: text
    fieldGroup: null
    handle: tipContent
    instructions: null
    name: 'Tip Content'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: recipeTip
name: 'Recipe Tip'
sortOrder: 2
