field: e2e7b70d-6b78-4367-a3b0-5287688756fa # Recipe Contents
fieldLayouts:
  28ee5a99-4743-44d1-a13a-38def437df5d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 1927b36e-a46c-4a8a-a2b0-008e657554f2 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3dbf20ac-316a-486a-bc91-06574b07d271
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c4cd97ce-a70a-4177-b089-b9171ff6155d # Image Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 38bc3e5b-38a1-4e08-aa2a-1591ea003bf4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4ebaba40-05b4-4ba2-bc57-f1a953f4f178
        userCondition: null
fields:
  1927b36e-a46c-4a8a-a2b0-008e657554f2: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      branchLimit: null
      defaultUploadLocationSource: 'volume:d7b1fdd8-6cdd-4245-bc99-a60a7955bccf' # Drinks
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: 1
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:d7b1fdd8-6cdd-4245-bc99-a60a7955bccf' # Drinks
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  c4cd97ce-a70a-4177-b089-b9171ff6155d: # Image Caption
    columnSuffix: ooiizasi
    contentColumnType: text
    fieldGroup: null
    handle: imageCaption
    instructions: null
    name: 'Image Caption'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: recipeImage
name: 'Recipe Image'
sortOrder: 1
