fieldLayouts:
  56262327-2e23-4723-a66b-f066e40a7fd5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 709c21b3-23ae-4880-a86c-e4fc81e3807b # Drink Style
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1f3e3083-3b06-4dd3-909e-1dc4d5180a85
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: 'Recipe Name'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6490ea1f-69a0-4471-88a6-640a2068d056
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e2e7b70d-6b78-4367-a3b0-5287688756fa # Recipe Contents
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 452fae89-d8f5-420d-abaf-71f17fbc2294
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 964ed106-6898-421c-bf48-3f134017f231
        userCondition: null
handle: recipes
hasTitleField: true
name: Recipes
section: 781ed780-e47c-4589-afee-6aa2faae2fda # Recipes
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
