defaultPlacement: end
fieldLayouts:
  5c42b330-2b95-4997-8ae6-ac5784a78e40:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 70fcbaa1-ae80-4aa9-ab18-162478c735ee
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6ab61fe6-d527-407e-aeff-650481b22cd7 # Style Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 49ecd285-44e4-40ee-b5c8-414c7d5ecae5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 44a8acaa-8a43-4343-a726-f9466652b89c
        userCondition: null
handle: drinkStyles
name: 'Drink Styles'
siteSettings:
  4817b4ec-c677-446f-9fd1-dc5973b84341: # craftycoffee
    hasUrls: true
    template: styles/_entry
    uriFormat: 'styles/{slug}'
structure:
  maxLevels: 5
  uid: 86eebac0-1b92-4383-8fe0-a1bcb19dab92
