columnSuffix: null
contentColumnType: string
fieldGroup: 5356ddf1-2f00-4039-8da3-ff44b9a95d36 # Drinks
handle: drinkImage
instructions: null
name: 'Drink Image'
searchable: true
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  branchLimit: null
  defaultUploadLocationSource: 'volume:d7b1fdd8-6cdd-4245-bc99-a60a7955bccf' # Drinks
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:d7b1fdd8-6cdd-4245-bc99-a60a7955bccf' # Drinks
  restrictedLocationSubpath: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Asset
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\assets\AssetCondition
  selectionLabel: 'Add a drink image'
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:d7b1fdd8-6cdd-4245-bc99-a60a7955bccf' # Drinks
  targetSiteId: null
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
