columnSuffix: null
contentColumnType: string
fieldGroup: 1f6a156e-1db3-44c7-9ded-39339f8390b0 # Recipes
handle: recipeContents
instructions: null
name: 'Recipe Contents'
searchable: false
settings:
  contentTable: '{{%matrixcontent_recipecontents}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
