dateModified: 1695329680
email:
  fromEmail: kate.stretton@platocreative.co.nz
  fromName: craftycoffee
  transportType: craft\mail\transportadapters\Sendmail
fs:
  drinks:
    hasUrls: true
    name: Drinks
    settings:
      path: '@webroot/images/drinks'
    type: craft\fs\Local
    url: '@web/images/drinks'
meta:
  __names__:
    0b8c3acf-2a4f-48f5-a154-c3f3747bd169: craftycoffee # craftycoffee
    2ee61b3e-b7ab-4366-8571-cb97794c9bd8: 'Public Schema' # Public Schema
    5f7dbe2d-7f53-4809-9c1f-e0ca7d1dc70a: 'About Craft Coffee' # About Craft Coffee
    6e54d5fd-e3e2-4d79-88f7-030cf8251024: Common # Common
    6fb714aa-68ab-4bfd-8c04-01c1c02c7b31: News # News
    8f07b957-3319-4804-ae6a-4888ba4c1891: 'Date Added' # Date Added
    8fa7dd00-3f97-4d93-83e9-3e303b5b76f0: 'News Body' # News Body
    9b844db6-8550-46df-8a12-a7f57081dd42: News # News
    096bf9e5-a1fe-44e5-a1cf-6c749ee0f69f: Drinks # Drinks
    262a7b35-583a-4d47-aefb-1e0227f60a90: 'About Crafty Coffee' # About Crafty Coffee
    4817b4ec-c677-446f-9fd1-dc5973b84341: craftycoffee # craftycoffee
    4841ffaa-e6cf-4c07-8b50-ade1d5dadb22: 'Drink Image' # Drink Image
    5356ddf1-2f00-4039-8da3-ff44b9a95d36: Drinks # Drinks
    60201c11-5efb-46ce-9ee3-1dcf37519019: Homepage # Homepage
    0449064c-a70d-4dab-b387-b3465c91abdd: Introduction # Introduction
    80302083-9c32-4c17-8262-f43f7cc66b55: 'Page Intro' # Page Intro
    a12fd5db-69eb-452c-b5f8-fdb5a5b0663c: '840x200 Thumb' # 840x200 Thumb
    b4a7fc6f-fa65-4549-acef-8f29fc2bec5a: Excerpt # Excerpt
    b84e397a-0266-493c-9c38-b7f47b0ffeac: News # News
    bbaf12ed-56e6-49eb-880e-2a03f5dc86bb: 'Page Copy' # Page Copy
    cfd26958-4ad4-4ba7-b535-39f49305125c: Drinks # Drinks
    d7b1fdd8-6cdd-4245-bc99-a60a7955bccf: Drinks # Drinks
    ee168fd8-9e56-483b-aed8-cbfce1fe1c80: About # About
    fc47bbf6-7571-4c82-9c3c-b3227603ebb1: Homepage # Homepage
    fdd40d5e-807e-46bb-a6ee-fa8aed786adf: Subtitle # Subtitle
plugins:
  feed-me:
    edition: standard
    enabled: true
    schemaVersion: 5.1.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
system:
  edition: pro
  live: true
  name: craftycoffee
  schemaVersion: 4.5.3.0
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
